backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: 'tutorials'
    label: 'Tutorials'
    folder: 'content/tutorials'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Updated Date', name: 'date', widget: 'datetime'}
      - {label: 'Description', name: 'description', widget: 'string', required: false}
      - {label: 'Image', name: 'image', widget: 'image', required: false}
      - label: 'Category'
        name: 'category'
        widget: 'select'
        default: 'tutorial'
        options: ['tutorial']
      - label: 'Author'
        name: 'author'
        widget: 'select'
        default: 'patrick'
        options: ['patrick', 'daniel']
      - label: 'Pinned'
        name: 'pinnedPosition'
        widget: 'number'
        min: 1
        max: 99
        valueType: 'int'
      - {label: 'Body', name: 'body', widget: 'markdown'}
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Description', name: 'description', widget: 'string', required: false}
      - {label: 'Image', name: 'image', widget: 'image', required: false}
      - label: 'Category'
        name: 'category'
        widget: 'select'
        default: 'blog'
        options: ['blog', 'video']
      - label: 'Author'
        name: 'author'
        widget: 'select'
        default: 'patrick'
        options: ['patrick', 'daniel']
      - {label: 'Body', name: 'body', widget: 'markdown'}
